hackbysarthak03/Hacktoberfest2023

CSS/index.css, index.html
=> Contributors

CSS/index.css, index.html
=> Add hover and animated

CSS/index.css, index.html
I have added hover feature and collapsable navbar items, if the screen size is reduced beyond a certain limit so as to improve css of the website. Kindly accept my PR
=> Added hover feature

index.html
name and github link updated as per the direction given
=> new contibutor added

CSS/index.css
added some media queries for responsiveness according to the issue #24
=> Added some media queries

CSS/index.css, index.html
=> Add CSS styling to Hero Section

index.html
simple contribution for hackathon2023
=> added simple contribution

CSS/index.css, index.html
- Adjusted top margin for the image above the logo to prevent overlap with the navbar.
- Modified the color of navbar links for improved visibility during hover.
- Edited the transition property from color-specific to all-encompassing, allowing better control over the transition time for font-weight changes during hover.
- Updated the text alignment of the central logo to resolve errors occurring when switching to mobile view.
=> My first contribution

CSS/index.css, index.html
The changes made were:
-Improved documentation
-Improved navbar look
-(fixed) hover effect on the "contributors" text on navbar
-Added a Seperator between the "Contributors for Hacktoberfest 2023" text and cards
-Improved positioning of the contributors' cards
-improved footer styling
added an extra card of my name as a contributor.
=> some major changes made to the site

CSS/index.css, index.html
I have changed the Github icons and also added a card. On hovering the icon it changes its color.
=> Changed Github icons

index.html
Thanks for giving your repo to make contribution
Happy coding
=> Added My card

index.html
I have created a type-writer effect at word CodeX to beautify it by placing this word in span tag and applied some js to it in the same index.html file
Happy Coding!
=> Typewriter effect at Codex

index.html
Hi! I'm Kartik , can you pls merge my pull request and also can you pls add tag of hacktoberfest and hacktoberfest accepted!
=> added profile

index.html
Thankyou for creating this repository and helping aspiring open source contributors.
=> PR for name and github profile

CSS/index.css, index.html
=> added contact form

CSS/index.css, index.html
changed the hovering effect on button
=> enhancing submit button

CSS/footer.css, CSS/index.css, index.html
As i have seen your actual footer is not responsive and good looking, so i build a simple, good looking responsive footer
Fixes  #26
You can see it through the link : (https://rko0211.github.io/Hacktoberfest2023/) 
I have created one extra footer.css file to differentiate between your code and mine. so, kindly review my PR and Merge it under **Hactoberfest 2023**. THank You...
=> Create Responsive Footer

CSS/index.css, index.html
=> Added Copyright

.github/workflows/static.yml, CSS/index.css, index.html, script.js
kindly review the change and accept the pull request 
I added loader in the beginning for 3 seconds
=> loader added 

index.html
I have added my name and github profile link in card div I read instructions and added code in the same way
Happy Coding!
=> added new card in index.html

index.html
I have added my name and GitHub profile link in index.html file following all the contribution guidelines. Please merge my PR with Hacktoberfest-accepted tag.
Happy coding!
=> Added my name and GitHub in index.html file
